CREATE DATABASE IF NOT EXISTS mealplan;

GRANT ALL PRIVILEGES on mealplan.*
TO 'it410mealplan'@'%' IDENTIFIED BY '410mealRockWad'
WITH GRANT OPTION;
USE mealplan;
CREATE TABLE Users (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL
)